#pragma config(Sensor, S1,     Rtrace,         sensorEV3_Color)
#pragma config(Sensor, S4,     Ltrace,         sensorEV3_Color)
#pragma config(Motor,  motorA,          Rarm,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          Larm,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorD,          left,          tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "void.h"

/*#define getTL getColorReflected(S4)
#define getTR getColorReflected(S1)

void setL(int power) {
	setMotorSpeed(left, power);
}

void setR(int power) {
	setMotorSpeed(right, power);
}

void drive(int power) {
	setL(power);
	setR(power);
}

void trace(int power){
	int color[2];
	color[0]=getTL;
	color[1]=getTR;
	setL((color[0]==10)?power/5:power);
	setR((color[1]==10)?power/5:power);
}*/


task main()
{



}
